name: Releases
on:
  push:
    branches:
      - main
jobs:
  changelog:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          preset: "conventionalcommits"  
          github-token: ${{ secrets.PA_TOKEN }}
          version-file: './package.json'
      - name: create release
        uses: elgohr/Github-Release-Action@v5
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}
        with:
          tag: ${{ steps.changelog.outputs.tag }}
          title: ${{ steps.changelog.outputs.tag }}